# MkDocs configuration for PyBrige documentation
site_name: PyBrige - Toolkit de Produtividade Python
site_url: https://juliobrige.github.io/pybrige/
site_description: Um toolkit de produtividade para desenvolvedores Python — automação, logging, configuração e utilitários.
site_author: Julio Benjamim Bernardo Brige
copyright: "Copyright © 2025 Julio Brige"

# Repository
repo_name: juliobrige/pybrige
repo_url: https://github.com/juliobrige/pybrige
edit_uri: edit/main/docs/

# Strict mode (build fails on warnings that break links)
strict: false

theme:
  name: material
  language: pt
  logo: assets/logo.png    # opcional (coloque em docs/assets/logo.png)
  favicon: assets/favicon.png  # opcional (docs/assets/favicon.png)
  palette:
    - scheme: default
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-4
        name: "Modo escuro"
    - scheme: slate
      primary: blue
      accent: cyan
      toggle:
        icon: material/brightness-7
        name: "Modo claro"
  features:
    - content.action.edit
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate

# Navigation
nav:
  - Início: index.md
  - Instalação: installation.md
  - Guias:
      - Primeiros Passos: guides/getting-started.md
      - Logging: guides/logging.md
      - CLI: guides/cli.md
      - Configuração: guides/configuration.md
  - API Reference: api-reference.md
  - Roadmap: roadmap.md
  - Contribuir: contributing.md

# Markdown extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      enable_creation_date: false
      type: date
      timezone: Africa/Maputo
      locale: pt
  - tags
  - privacy

# Extra social links (renderiza no footer/header)
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/juliobrige
      name: "GitHub"
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/pybrige/
      name: "PyPI"
    - icon: material/web
      link: https://juliobrige.github.io/pybrige/
      name: "Site da Documentação"

# Optionally serve without directory-style URLs on Windows (evita alguns avisos)
# use_directory_urls: false

# Extra assets (coloque em docs/assets/ se quiser usar)
# extra_css:
#   - assets/extra.css
# extra_javascript:
#   - assets/extra.js
